syntax = "proto3";

package spec.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";

option go_package = "github.com/stupside/DATA-intensive/assignment-4/proto/gen/spec/v1;v1";

message OnboardRequest {
  bytes csr = 1 [(buf.validate.field).bytes.min_len = 1];
}
message OnboardResponse {
  bytes certificate = 1;
}

service AuthService {
  // Onboard is used by the device to onboard itself to the system
  rpc Onboard(OnboardRequest) returns (OnboardResponse) {
    option (google.api.http) = {post: "/api/v1/device/onboard"};
  }
}
